src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez définir le titre")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Veuillez décrire l'événement")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive(message="Chiffre impossible !")
     * @Assert\NotBlank(message="Veuillez entrer le prix de l'atelier")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez entrer le nom du formateur")
     */
    private $formatorName;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Veuillez entrer le nombre maximum de participants")
     * @Assert\Positive(message="Chiffre impossible !")
     */
    private $nbMembers;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EventType", inversedBy="events", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $eventType;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="event", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $photos;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="events")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\WorkshopDate", mappedBy="event", orphanRemoval=true)
     */
    private $workshopDates;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="workshops")
     * @ORM\JoinColumn(nullable=true)
     */
    private $participants;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="event", cascade={"remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\GiftAmount", mappedBy="event", cascade={"remove"})
     */
    private $giftAmounts;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->workshopDates = new ArrayCollection();
        $this->participants = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->giftAmounts = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getEventType(): ?EventType
    {
        return $this->eventType;
    }

    public function setEventType(?EventType $eventType): self
    {
        $this->eventType = $eventType;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setEvent($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getEvent() === $this) {
                $photo->setEvent(null);
            }
        }

        return $this;
    }

    public function getFormatorName(): ?string
    {
        return $this->formatorName;
    }

    public function setFormatorName(string $formatorName): self
    {
        $this->formatorName = $formatorName;

        return $this;
    }

    public function getNbMembers(): ?int
    {
        return $this->nbMembers;
    }

    public function setNbMembers(int $nbMembers): self
    {
        $this->nbMembers = $nbMembers;

        return $this;
    }

    public function getFirstPhoto()
    {
        return $this->photos->first();
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNote(): ?float
    {
        return $this->note;
    }

    public function setNote(?float $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getWorkshopDates()
    {
        return $this->workshopDates;
    }

    public function addWorkshopDate(WorkshopDate $workshopDate): self
    {
        if (!$this->workshopDates->contains($workshopDate)) {
            $this->workshopDates[] = $workshopDate;
            $workshopDate->setEvent($this);
        }

        return $this;
    }

    public function removeWorkshopDate(WorkshopDate $workshopDate): self
    {
        if ($this->workshopDates->contains($workshopDate)) {
            $this->workshopDates->removeElement($workshopDate);
            // set the owning side to null (unless already changed)
            if ($workshopDate->getEvent() === $this) {
                $workshopDate->setEvent(null);
            }
        }

        return $this;
    }

    public function getFirstWorkshopDates()
    {
        if (!$this->workshopDates->first()) {
            return false;
        }
        return $this->workshopDates->first();
    }

    public function getAllWorkshopDates()
    {
        if ($this->workshopDates->count() <= 0) {
            return false;
        }
        return $this->workshopDates;
    }

    /**
     * @return Collection|User[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(User $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(User $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|GiftAmount[]
     */
    public function getGiftAmounts(): Collection
    {
        return $this->giftAmounts;
    }

    public function addGiftAmount(GiftAmount $giftAmount): self
    {
        if (!$this->giftAmounts->contains($giftAmount)) {
            $this->giftAmounts[] = $giftAmount;
            $giftAmount->setEvent($this);
        }

        return $this;
    }

    public function removeGiftAmount(GiftAmount $giftAmount): self
    {
        if ($this->giftAmounts->contains($giftAmount)) {
            $this->giftAmounts->removeElement($giftAmount);
            // set the owning side to null (unless already changed)
            if ($giftAmount->getEvent() === $this) {
                $giftAmount->setEvent(null);
            }
        }

        return $this;
    }
}

src/Controller/Back/EventController.php
<?php

namespace App\Controller\Back;

use App\Entity\Event;
use App\Entity\Photo;
use App\Entity\WorkshopDate;
use App\Form\EventFormType;
use App\Repository\EventRepository;
use App\Repository\ReservationRepository;
use App\Repository\WorkshopDateRepository;
use App\Services\File\UploadFile;
use App\Services\Slug;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/admin")
 */
class EventController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/evenements/{page}", defaults={"page"=1}, requirements={"page"="\d+"}, name="admin_event_list")
     */
    public function list(int $page, EventRepository $eventRepository, PaginatorInterface $paginator)
    {
        $pagination = $paginator->paginate(
            $eventRepository->findBy([], ['id' => 'DESC']), /* query NOT result */
            $page, /*page number*/
            25 /*limit per page*/
        );

        return $this->render('back/event/list.html.twig', [
            'events' => $pagination,
        ]);
    }

    /**
     * @Route("/evenements/ajouter", name="admin_event_add")
     */
    public function add(Request $request, SessionInterface $session)
    {
        $event = new Event();
        $form = $this->createForm(EventFormType::class, $event, ['enterpriseField' => true,'csrf_protection' => false])->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($event->getPhotos() as $photo) {

                $imageName = UploadFile::uploadImageEvent($photo->getUrl());
                $photo->setUrl($imageName);
                $photo->setEvent($event);

                $this->em->persist($photo);
            }

            foreach ($session->all() as $dates) {
                $date = explode('--', $dates);

                if (preg_match('/(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})/', $date[0])) {
                    $dateStart = new \DateTime($date[0]);
                    $dateEnd = new \DateTime($date[1]);

                    $interval = $dateStart->diff($dateEnd);
                    $minutes = $interval->i > 0 ? $interval->i : '00';
                    $duration = $interval->h.'h'.$minutes.'min';

                    $workshopDate = new WorkshopDate();
                    $workshopDate->setStartAt($dateStart);
                    $workshopDate->setEndAt($dateEnd);
                    $workshopDate->setDuration($duration);
                    $workshopDate->setEvent($event);
                    $event->addWorkshopDate($workshopDate);

                    $this->em->persist($workshopDate);

                    $session->remove($dates);
                }
            }

            $slug = Slug::slugify($event->getTitle());
            $event->setSlug($slug);

            $this->em->persist($event);
            $this->em->flush();

            return $this->redirectToRoute('admin_event_list', ['action' => 'success']);
        }

        return $this->render('back/event/add.html.twig', [
            'form' => $form->createView(),
            'event' => $event
        ]);
    }

    /**
     * @Route("/evenements/editer/{id}", name="admin_event_edit")
     */
    public function edit(Request $request, SessionInterface $session, Event $event, WorkshopDateRepository $workshopDateRepository)
    {
        $form = $this->createForm(EventFormType::class, $event, ['enterpriseField' => true, 'csrf_protection' => false])->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($event->getPhotos() as $photo) {

                if (!$photo->getEvent()) {
                    $imageName = UploadFile::uploadImageEvent($photo->getUrl());
                    $photo->setUrl($imageName);
                    $photo->setEvent($event);

                    $this->em->persist($photo);
                }
            }

            foreach ($session->all() as $dates) {
                $date = explode('--', $dates);

                if (preg_match('/(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})/', $date[0])) {
                    $dateStart = new \DateTime($date[0]);
                    $dateEnd = new \DateTime($date[1]);

                    $interval = $dateStart->diff($dateEnd);
                    $minutes = $interval->i > 0 ? $interval->i : '00';
                    $duration = $interval->h.'h'.$minutes.'min';

                    $workshopDate = new WorkshopDate();
                    $workshopDate->setStartAt($dateStart);
                    $workshopDate->setEndAt($dateEnd);
                    $workshopDate->setDuration($duration);
                    $workshopDate->setEvent($event);
                    $event->addWorkshopDate($workshopDate);

                    $this->em->persist($workshopDate);
                }
            }
            $session->clear();

            $slug = Slug::slugify($event->getTitle());
            $event->setSlug($slug);
            $event->setEventType($form->get('eventType')->getData());

            $this->em->persist($event);
            $this->em->flush();

            return $this->redirectToRoute('admin_event_list', ['action' => 'success']);
        }

        return $this->render('back/event/edit.html.twig', [
            'form' => $form->createView(),
            'workshopDates' => $workshopDateRepository->getDatesEvent($event),
            'event' => $event
        ]);
    }

    /**
     * @Route("/deposer-atelier/removedate/{id}", name="back_event_remove_dates")
     */
    public function removeDate(Request $request, Event $event, SessionInterface $session)
    {
        $session->clear();
        foreach ($event->getWorkshopDates() as $date) {
            $this->em->remove($date);
        }

        $this->em->flush();

        return new JsonResponse([
            'message' => 'ok'
        ]);
    }

    /**
     * @Route("/evenements/suppression/{id}", name="admin_event_remove")
     */
    public function remove(Event $event)
    {
        $this->em->remove($event);
        $this->em->flush();

        return $this->redirectToRoute('admin_event_list');
    }

    /**
     * @Route("/reservations/{page}", defaults={"page"=1}, requirements={"page"="\d+"}, name="back_reservations_list")
     */
    public function listReservations(int $page, PaginatorInterface $paginator, ReservationRepository $reservationRepository)
    {
        $pagination = $paginator->paginate(
            $reservationRepository->findBy([], ['reservedAt' => 'DESC']), /* query NOT result */
            $page, /*page number*/
            25 /*limit per page*/
        );

        return $this->render('back/reservation/list.html.twig', [
            'reservations' => $pagination
        ]);
    }
}

templates/front/event/events_category.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% if eventType.name is defined %}Ateliers de la catégorie {{ eventType.name }}{% else %}Tous les ateliers{% endif %}{% endblock %}
{% block description %}
    {% if eventType.name is defined %}
    {{ events|length }} ateliers disponibles dans la catégorie {{ eventType.name }}, participez vous aussi à ces ateliers !
    {% else %}
        {{ events|length }} ateliers disponibles au total, participez vous aussi à ces ateliers !
    {% endif %}
{% endblock %}

{% block body %}
    <section class="hero_in tours" style="background-image:url({{ asset('img/cuisine-enfant-categorie.jpg') }});background-position:top;background-repeat:no-repeat;background-size:cover">
        <div class="wrapper">
            <div class="container">
                <h1 class="fadeInUp"><span></span>{{ eventType }}</h1>
            </div>
        </div>
    </section>
    <!--/hero_in-->s

    <div class="container margin_60_35">
        <div class="col-lg-12 mb-5">
            {{ include('front/inc/searchbar.html.twig') }}
            <!-- /row -->
        </div>
        <!-- /custom-search-input-2 -->

        <div class="container margin_60_35">
            {% for event in pagination %}
                <div class="box_list">
                    <div class="row no-gutters">
                        <div class="col-lg-5">
                            <figure>
                                <small>{{ event.eventType.name }}</small>
                                <a href="{{ path('front_event_single', {'id': event.id, 'category': event.eventType.slug, 'slug': event.slug}) }}"><img src="{{ asset( constant('App\\Services\\File\\UploadFile::IMAGE_UPLOAD_DIR')) ~ event.firstPhoto.url }}" class="img-fluid" alt="" width="800" height="533"><div class="read_more"><span>Voir</span></div></a>
                            </figure>
                        </div>
                        <div class="col-lg-7">
                            <div class="wrapper">
                                <h3><a href="{{ path('front_event_single', {'id': event.id, 'category': event.eventType.slug, 'slug': event.slug}) }}">{{ event.title }}</a></h3>
                                <p>{{ event.description|slice(0,130) }}</p>
                                <span class="price"><i class="icon_house mr-1 mt-2" style="color:#800200"></i> {{ event.user.zipCode }}, {{ event.user.city }}</span><br>
                                <span class="price mt-1"><i class="icon_creditcard mr-1" style="color:#800200"></i>  <strong>{{ event.price }}€</strong> / par personne</span><br>
                                {% if app.user and app.user.moneyGift > 0 %}{% set priceEventWithGift = event.price - app.user.moneyGift %}<span class="price mt-1"><i class="icon_gift mr-1" style="color:#800200"></i> <strong>{{ priceEventWithGift > 0 ? priceEventWithGift : 0 }}€</strong>  avec votre bon cadeau{% endif %}</span><br>
                            </div>
                            <ul>
                                <li><i class="icon_clock_alt"></i> {% if event.getFirstWorkshopDates %}{{ event.getFirstWorkshopDates.duration }}{% endif %}</li>
                                <li><div class="rating"><span>
                                            {% for i in range(1, 10) %}
                                            {% if loop.index <= event.note %}
                                                <i class="icon_star voted"></i>
                                            {% else %}
                                                <i class="icon_star"></i>
                                            {% endif %}
                                            {% endfor %}</span>(<strong style="font-size:1.2em">{{ event.comments|length }} notes</strong>)
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% else %}
                <p class="text-center">Aucun atelier ne correspond aux critères de recherche.</p>
            {% endfor %}
        </div>
        <!-- /isotope-wrapper -->

        <p class="text-center"><div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div></p>

    </div>
    <!-- /container -->

    {{ include('front/inc/helpbar.html.twig') }}
    <!-- /bg_color_1 -->
{% endblock %}

templates/front/event/single.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.title }} | PassionAtelier{% endblock %}
{% block description %}{000{% endblock %}

{% block style %}
    {% if app.request.attributes.get('_route') == 'front_event_single' %}
        <style>
            .mfp-content{height:60%;}
        </style>
    {% endif %}
{% endblock %}

{% block body %}
    <section class="hero_in tours_detail" style="background-image:url({{ asset(constant('App\\Services\\File\\UploadFile::IMAGE_UPLOAD_DIR') ~ event.firstPhoto.url) }});background-position:center;background-repeat:no-repeat;background-size:cover">
        <div class="wrapper">
            <div class="container">
                <h1 class="fadeInUp"><span></span>{{ event.title }}</h1>
            </div>
            <span class="magnific-gallery">
                {% for photo in event.photos %}
                    <a href="{{ asset( constant('App\\Services\\File\\UploadFile::IMAGE_UPLOAD_DIR')) ~ event.firstPhoto.url }}" class="btn_photos" title="Photo title" data-effect="mfp-zoom-in">Voir les photos</a>
                {% endfor %}
            </span>
        </div>
    </section>
    <!--/hero_in-->

    <!-- Sign In Popup -->
    <div id="sign-in-dialog" class="zoom-anim-dialog mfp-hide" style="max-width:50%;height:100%;">
        <div class="small-dialog-header" style="width:100%">
            <h3>Dates de l'atelier</h3>
        </div>
        <div class="list_articles add_bottom_30 clearfix">
            <div class="row">
                <div class="col-md-12" style="height:400px;overflow-y: scroll;">
                    {% for date in workshopDates %}
                        {% if date(date.startAt) > date() %}
                        <div class="row border-bottom pt-2 pb-2 mt-2">
                            <div class="col-md-9 pt-1">
                                {{ date.startAt|format_datetime('full', 'none', locale='fr') }} de {{ date.startAt|date('H:i') }} à {{ date.endAt|date('H:i') }}<br>
                                {% set places = date.event.nbMembers - date.reservations|length %}
                                {% if places <= 0 %}
                                    Aucune place disponible
                                {% else %}
                                    {{ date.event.nbMembers - date.reservations|length }} places restantes
                                {% endif %}
                            </div>
                            <div class="col-md-3">
                                {% if places <= 0 %}
                                    <button type="button" class="btn btn-danger">Complet</button>
                                {% else %}
                                    <a href="{{ path('front_reservation_informations', {'id': date.id}) }}" class="btn" style="background:#802826;color:white">Réserver</a>
                                {% endif %}
                            </div>
                        </div>
                        {% endif %}
                    {% else %}
                        <p>Aucune date prévue pour le moment.</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <!--form -->
    </div>


    <div class="bg_color_1">
        <nav class="secondary_nav sticky_horizontal">
            <div class="container">
                <ul class="clearfix">
                    <li><a href="#description" class="active">Description</a></li>
                    <li><a href="#reviews">Notes & avis</a></li>
                    <li><a href="#sidebar">Booking</a></li>
                </ul>
            </div>
        </nav>
        <div class="container margin_60_35">
            <div class="row">
                <div class="col-lg-8">
                    <section id="description">
                        <h2>Description</h2>
                        <p>{{ event.description }}</p>
                    </section>
                    <!-- /section -->

                    <section id="reviews">
                        <h2>Notes & commentaires</h2>
                        <div class="reviews-container">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div id="review_summary">
                                        <strong>{{ event.note|number_format(1, '.') }}</strong>
                                        <em>{{ event.comments|length }} notes</em>
                                    </div>
                                </div>

                            </div>
                            <!-- /row -->
                        </div>

                        <hr>

                        <div class="add-review">
                            <h5>Notez et commentez</h5>
                            {% for message in app.flashes('notice') %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                            {% endfor %}
                            {% if eventCommented %}
                                <p>{{ messageComment }}</p>
                            {% else %}
                            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        {{ form_label(form.noteUser) }}
                                        <div class="custom-select-form">
                                            {{ form_widget(form.noteUser, {'attr': {'id':'rating_review', 'class':'wide'}}) }}
                                        </div>
                                    </div>
                                    <div class="form-group col-md-12">
                                        {{ form_row(form.content, {'attr': {'class': 'form-control', 'rows':5}}) }}
                                    </div>
                                    <div class="form-group col-md-12 add_top_20">
                                        <input type="submit" value="Ajouter" class="btn_1" id="submit-review">
                                    </div>
                                </div>
                            {{ form_end(form) }}
                            {% endif %}
                        </div>

                        <div class="reviews-container">
                            {% for comment in event.comments %}
                            <div class="review-box clearfix">
                                <figure class="rev-thumb"><img src="img/avatar1.jpg" alt="">
                                </figure>
                                <div class="rev-content">
                                    <div class="rating">
                                        {% for i in range(1, 10) %}
                                            {% if loop.index <= comment.noteUser %}
                                                <i class="icon_star voted"></i>
                                            {% else %}
                                                <i class="icon_star"></i>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                    <div class="rev-info">
                                        {{ comment.user.firstName }} – {{ comment.publishedAt|format_datetime('full', 'none', locale='fr') }} :
                                    </div>
                                    <div class="rev-text">
                                        <p>
                                            {{ comment.content }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                        <!-- /review-container -->
                    </section>
                    <!-- /section -->
                    <hr>
                </div>
                <!-- /col -->

                <aside class="col-lg-4" id="sidebar">
                    <div class="box_detail booking">
                        <div class="price">
                            <span>{{ event.nbMembers }} <small>personnes max.</small></span>
                        </div>
                        <div class="price">
                            <span>{{ event.price }}€ <small>/ personne</small></span>
                            <div class="score"><span>Note<em>{{ event.comments|length }} notes</em></span><strong>{{ event.note|number_format(1, '.') }}</strong></div>
                        </div>
                        {% if app.user and app.user.moneyGift > 0 %}
                            {% set priceEventWithGift = event.price - app.user.moneyGift %}
                            <div class="price">
                                <span>{{ priceEventWithGift > 0 ? priceEventWithGift : 0 }}€ <small>/ en utilisant ta carte cadeau</small></span>
                            </div>
                        {% endif %}
                        <div class="price mb-0">
                            <span><a href="#sign-in-dialog" id="button-display-dates" class="btn" style="background:#802826;color:white">Réserver</a></span>
                        </div>
                        {% if app.session.get('btnOffertWorkshop') %}
                            <div class="price mt-2 mb-0 mt-5" style="border-bottom:0">
                                <a href="{{ path('front_gift_choice_workshop', {'id': event.id}) }}" class="btn" id="submit-review" style="color:white;font-weight:600;font-size:inherit;background:yellowgreen">
                                    <i class="icon_gift"></i> Offrir en carte cadeau</a>
                            </div>
                        {% endif %}
                        <div class="price pt-3">
                            <span><small style="font-size:0.6em">Adresse</small></span>
                            <div class="score"><span>{{ event.user.adress }}<br> {{ event.user.zipCode }}, {{ event.user.city }}</span></div>
                        </div>
                    </div>
                </aside>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bg_color_1 -->
{% endblock %}

{% block javascript %}
{{ parent() }}
<!-- Map -->
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script src="{{ asset('js/map_single_tour.js') }}"></script>
<script src="{{ asset('js/infobox.js') }}"></script>
<script src="{{ asset('js/input_qty.js') }}"></script>
{% endblock %}